apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name: resource-spec
  labels:
    app: rapido-application
    env: uat
  namespace: testing
  annotations: 
    repo: 934545598565.dkr.ecr.ap-south-1.amazonaws.com/csstemp
spec:
  minReadySeconds: 6
  replicas: 4
  selector:
    matchLabels:
      app: rep-cont-match
  template:
    metadata:
      name: cont-define
      labels:
        app: rep-cont-match
    spec:
      containers:
        - name: my-containers
          image: 934545598565.dkr.ecr.ap-south-1.amazonaws.com/csstemp:1.10
          ports:
            - containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            exec:
              command:
                ["echo hello my replica"]
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              cpu: 200m
              memory: 350Mi
            limits:
              cpu: 500m 
              memory: 1000Mi

              