apiVersion: v1
kind: Service
metadata:
  name: service-name
  labels:
    app: rapido-application
  namespace: testing
spec:
  selector: 
    app: rapido-application   # This must match your Pod/Deployment labels
  type: LoadBalancer
  ports:
    - name: port-define
      port: 80
      protocol: TCP
      targetPort: 80

