apiVersion: v1
kind: Service
metadata:
  name: service-name
  namespace: testing
spec:
  selector: 
    app: rep-cont-match   # This must match your Pod/Deployment labels
  type: LoadBalancer
  ports:
    - name: port-define
      port: 80
      protocol: TCP
      targetPort: 80

